# Generated by Django 5.2.5 on 2025-08-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tella', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesurclient',
            name='fideback',
            field=models.CharField(blank=True, max_length=500, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='client',
            name='numberPhone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mesurclient',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='mesurclient',
            name='habit',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='mesurclient',
            name='panthalon',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
