# Generated by Django 5.2.5 on 2025-08-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tella', '0002_mesurclient_fideback_alter_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesurclient',
            name='fideback',
        ),
    ]
